version: '3'
services:
  database:
    image: mongo
    container_name: 'wtw-mongodb'
    restart: always
    volumes: 
      - mongodbdata:/data/db
    ports:
      - 27017:27017
  
  back:
    image: cake1234/wtw-backend:1.0.4
    container_name: 'wtw-backend'
    depends_on:
      - "database"
    restart: always
    ports: 
      - 4001:4001
  
  front:
    image: cake1234/wtw-frontend:1.0.4
    container_name: 'wtw-frontend'
    depends_on:
      - "back"
    restart: always
    ports:
      - 80:80

volumes:
  mongodbdata: